# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_category_id',
            new_name='restaurant_category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
